import Events from '../models/eventSchema.js';

export const createEvents = async () => {
	const events = [
		{
			title: 'Music Concert',
			description: 'An amazing night of live music.',
			startDate: new Date('2024-11-01T18:00:00Z'),
			endDate: new Date('2024-11-01T21:00:00Z'),
			location: 'Stadium A',
			maxAttendees: 500,
			attendees: [],
			isPublic: true,
			secretInfo: 'VIP access available',
			isPaymentRequired: true,
			price: 50,
			isRegisterRequired: true,
			needApproval: false,
			ageLimit: 18,
			authorId: 'z23c3m086sord9mt312xgb7',
		},
		{
			title: 'Art Exhibition',
			description: 'A showcase of modern art.',
			startDate: new Date('2024-12-05T10:00:00Z'),
			endDate: new Date('2024-12-05T17:00:00Z'),
			location: 'Gallery B',
			maxAttendees: 200,
			attendees: [],
			isPublic: false,
			secretInfo: 'Artist meet-and-greet available',
			isPaymentRequired: false,
			isRegisterRequired: true,
			needApproval: true,
			ageLimit: 12,
			authorId: '273bv9nct85zvbot7ne4s',
		},
		{
			title: 'Coding Workshop',
			description: 'Learn to code with experts.',
			startDate: new Date('2024-11-15T09:00:00Z'),
			endDate: new Date('2024-11-15T17:00:00Z'),
			location: 'Tech Hub',
			maxAttendees: 100,
			attendees: [],
			isPublic: true,
			secretInfo: 'Bring your own laptop',
			isPaymentRequired: false,
			isRegisterRequired: true,
			needApproval: false,
			ageLimit: 16,
			authorId: 'gg6p2vg837zvog5n83w7',
		},
		{
			title: 'Charity Run',
			description: '5K run for charity.',
			startDate: new Date('2024-11-20T07:00:00Z'),
			endDate: new Date('2024-11-20T11:00:00Z'),
			location: 'City Park',
			maxAttendees: 1000,
			attendees: [],
			isPublic: true,
			secretInfo: 'Free T-shirts for participants',
			isPaymentRequired: true,
			price: 10,
			isRegisterRequired: true,
			needApproval: false,
			ageLimit: 0,
			authorId: '0v5t6mgnw83v03n65w8g7',
		},
		{
			title: 'Food Festival',
			description: 'Explore delicious cuisines from around the world.',
			startDate: new Date('2024-11-10T12:00:00Z'),
			endDate: new Date('2024-11-10T20:00:00Z'),
			location: 'Food Plaza',
			maxAttendees: 300,
			attendees: [],
			isPublic: true,
			secretInfo: 'Free tasting session at 2 PM',
			isPaymentRequired: false,
			isRegisterRequired: false,
			needApproval: false,
			ageLimit: 0,
			authorId: 'o58vb3w765n9lgwmtcv37i67',
		},
		{
			title: 'Yoga Retreat',
			description: 'A peaceful day of yoga and meditation.',
			startDate: new Date('2024-11-25T07:30:00Z'),
			endDate: new Date('2024-11-25T17:00:00Z'),
			location: 'Mountain Lodge',
			maxAttendees: 50,
			attendees: [],
			isPublic: false,
			secretInfo: 'Personalized yoga mats provided',
			isPaymentRequired: true,
			price: 80,
			isRegisterRequired: true,
			needApproval: true,
			ageLimit: 18,
			authorId: 'm1b2v9ng45tylg59xz09',
		},
		{
			title: 'Film Festival',
			description: 'A celebration of independent films.',
			startDate: new Date('2024-11-18T10:00:00Z'),
			endDate: new Date('2024-11-18T22:00:00Z'),
			location: 'Cinema Complex',
			maxAttendees: 400,
			attendees: [],
			isPublic: true,
			secretInfo: 'VIP tickets include backstage access with filmmakers',
			isPaymentRequired: true,
			price: 25,
			isRegisterRequired: false,
			needApproval: false,
			ageLimit: 15,
			authorId: 'r98xg4vbc24xz89ty7wm',
		},
		{
			title: 'Photography Workshop',
			description: 'Learn professional photography techniques.',
			startDate: new Date('2024-12-02T08:00:00Z'),
			endDate: new Date('2024-12-02T16:00:00Z'),
			location: 'Studio X',
			maxAttendees: 30,
			attendees: [],
			isPublic: true,
			secretInfo: 'Includes free access to photography gear',
			isPaymentRequired: false,
			isRegisterRequired: true,
			needApproval: true,
			ageLimit: 16,
			authorId: '57qgb5v89rf6xt8wl3b9',
		},
		{
			title: 'Cooking Masterclass',
			description: 'Hands-on experience with gourmet chefs.',
			startDate: new Date('2024-12-10T14:00:00Z'),
			endDate: new Date('2024-12-10T19:00:00Z'),
			location: 'Gourmet Kitchen',
			maxAttendees: 20,
			attendees: [],
			isPublic: false,
			secretInfo: 'Free recipe book for attendees',
			isPaymentRequired: true,
			price: 100,
			isRegisterRequired: true,
			needApproval: true,
			ageLimit: 18,
			authorId: 'v36hfg9nbc72m5h67w5x',
		},
		{
			title: 'Tech Startup Pitch Night',
			description: 'Pitch your startup to investors.',
			startDate: new Date('2024-11-22T18:00:00Z'),
			endDate: new Date('2024-11-22T21:00:00Z'),
			location: 'Business Hub',
			maxAttendees: 150,
			attendees: [],
			isPublic: true,
			secretInfo: 'Top 3 pitches get funding offers',
			isPaymentRequired: false,
			isRegisterRequired: true,
			needApproval: true,
			ageLimit: 21,
			authorId: 't9m82x9l23v6rfng3v6z',
		},
	];

	try {
		await Events.insertMany(events);
		console.log('5 events created successfully!');
	} catch (error) {
		console.error('Error creating events:', error);
	}
};
